# QUESTION2
# The Base: Use python:3.9-alpine.
# The Metadata: Add a LABEL that sets the developer to your name.
# The Environment: Create an ENV variable called DEPT_NAME with a default value of "General".
# The Build Logic: Create an ARG variable called BUILD_VERSION.
# The App Code: * Create a file named greet.py.
# It should print: "Hello from [DEPT_NAME] department. Running version [BUILD_VERSION]."
# Note: Use os.getenv for the ENV and a simple string replacement or file write for the ARG.
# The Execution: Set the WORKDIR to /app and make sure the script runs when the container starts.

FROM python:3.9-alpine
LABEL developer = "harishreddy"
#LABEL Description = "Level 1 Example 2 - Environment Variables"
ENV DEPT_NAME = "General"
# ARG is for build-time
ARG BUILD_VERSION
# PRO TIP: We move the ARG value into an ENV so the app can see it later
ENV Version=$BUILD_VERSION
WORKDIR /app
COPY greet.py .
CMD ["python", "greet.py"]