# QUESTION2
# The Base: Use python:3.9-alpine.
# The Metadata: Add a LABEL that sets the developer to your name.
# The Environment: Create an ENV variable called DEPT_NAME with a default value of "General".
# The Build Logic: Create an ARG variable called BUILD_VERSION.
# The App Code: * Create a file named greet.py.
# It should print: "Hello from [DEPT_NAME] department. Running version [BUILD_VERSION]."
# Note: Use os.getenv for the ENV and a simple string replacement or file write for the ARG.
# The Execution: Set the WORKDIR to /app and make sure the script runs when the container starts.

FROM python:3.9-alpine
LABEL developer = "harishreddy"
#LABEL Description = "Level 1 Example 2 - Environment Variables"
ENV DEPT_NAME = "General"
# ARG is for build-time
ARG BUILD_VERSION
# PRO TIP: We move the ARG value into an ENV so the app can see it later
ENV Version=$BUILD_VERSION
WORKDIR /app
COPY greet.py .
CMD ["python", "greet.py"]

# output of the code

# ubuntu@ip-172-31-25-105:~/DOCKER-PRACTICE/level2$ docker run --name harish -d greeter-app
# ccbdaba1b97f557f9d86f7b25870838b51e62e4bc08859b4a75fbb75431f9aa3
# ubuntu@ip-172-31-25-105:~/DOCKER-PRACTICE/level2$ docker ps
# CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
# ubuntu@ip-172-31-25-105:~/DOCKER-PRACTICE/level2$ docker ps -a
# CONTAINER ID   IMAGE         COMMAND             CREATED         STATUS                     PORTS     NAMES
# ccbdaba1b97f   greeter-app   "python greet.py"   8 seconds ago   Exited (0) 7 seconds ago             harish

# ubuntu@ip-172-31-25-105:~/DOCKER-PRACTICE/level2$ docker run greeter-app
# Hello from = General department. Running version 0.0.0.

# ubuntu@ip-172-31-25-105:~/DOCKER-PRACTICE/level2$ docker run -e DEPT_NAME="Marketing" greeter-app
# Hello from Marketing department. Running version 0.0.0.
# ubuntu@ip-172-31-25-105:~/DOCKER-PRACTICE/level2$
