#To get you started on Level 1, I want you to try writing a Dockerfile for a basic Node.js app.
# Challenge: Write a Dockerfile that:
# Starts from node:18-alpine.
# Sets the workdir to /home/node/app.
# Uses ARG to set a VERSION variable (default to "1.0").
# Copies a package.json and server.js.
# Runs npm install.
# Exposes port 3000.
# Runs the command node server.js.

# Base image
FROM node:18-alpine
# Set the working directory
WORKDIR /usr/src/app
#Copy dependencies first (Optimization/Caching)
COPY package.json ./
# Install dependencies
RUN npm install -y
# Copy the rest of the source code (after npm install)
COPY . .
# Document the port
EXPOSE 3000
# The execution command
CMD ["node", "server.js"]

